language: node_js

node_js:
  - "8"
  - "6"
  - "4"

sudo: false
cache:
  directories:
    - node_modules

matrix:
  fast_finish: true

script: "make test-travis"
after_script: "npm install coveralls@2.12.0 && cat ./coverage/lcov.info | coveralls"

notifications:
  email:
    on_success: change
    on_failure: always
